### ISSUE TITLE
Capstone Project: Kanban board

### ISSUE THREAD

**Issue by Leandro-Barretoo** [Hector096/FlipCart-backend#27]
We are a team of 3 members:
- @Hector096
- @emmanuellekamwa 
- @Leandro-Barretoo 

This is how kanban board for the capstone project.

https://github.com/Hector096/FlipCart-backend/projects/1

![capstone-kanban](https://user-images.githubusercontent.com/72808808/157063933-f1654117-11fc-4f6e-8bce-d6c1b3bec222.png)

Thank you for the review.

**Comment by MuriloRoque** [comment]
Hi @Leandro-Barretoo, @Hector096, @emmanuellekamwa,

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [ ] Please put a screenshot of your Kanban board in this issue's description, just like it's mentioned in [the requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).
- [ ] Please mention the names of each team members in the issue's description, it looks like you meant to do it but might have forgotten to add.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @Leandro-Barretoo, @emmanuellekamwa, @Hector096,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
